### PR TITLE
Add title and improve one fix

### PR DESCRIPTION
**Pull request by ChaoticRoman**
* Adding a title
* remove unnecessary call

If I need to reflect the change elsewhere, let me know.

### CODE REVIEW

**Comment by dosisod** [comment]
Thank you @ChaoticRoman for opening this PR! The `docs/checks.md` file can't be edited directly because it is automatically generated, so to apply your changes, add the following to the `docs/gen_checks.py` file (at the bottom):

```python
with (Path(__file__).parent / "checks.md").open("w+") as f:
    # add this line:
    f.write("# Available Checks\n")

    for k, v in sorted(docs.items()):
        f.write("\n")
        f.write(v)
```

Here I used "Activated Checks" since some of these checks are disabled by default, so it's more accurate to say that this is *all* of the checks that you could enable.

As for `bool(value)`, update the docstring in `refurb/checks/readability/no_double_not.py`:

https://github.com/dosisod/refurb/blob/b8d9239c1595b4db3995750741bbe854eaa35837/refurb/checks/readability/no_double_not.py#L22-L25

Then make sure to run `make docs` to update the documentation! This process isn't documented, so I will make sure to add documentation on how to update this file.

**Comment by dosisod** [comment]
Thank you!

**Comment by dosisod** [comment]
Also, I noticed that you changed the `bool(x)` error message as well. This is problematic in the following situations:

```python
x = 123
y = not not x
```

In the above example, `y` gets set to `True`. But, if it was defined as `x` instead, the value of `y` would become `123`. With `if` blocks this isn't an issue since `123` would be converted to a boolean anyways, but for all other cases this would be an issue.

My recommendation: Change the error message back to `bool(x)` so that user code behaves the same in all cases. I will look into how to handle the special case of `not not` being used in `if` blocks, but for now let's keep it as `bool(x)`. Thanks!

Other than that this PR is ready to be merged.

**Comment by ChaoticRoman** [comment]
Fixed.

**Review by dosisod — APPROVED** [review]

**Pull request merged**
