### PR TITLE
fix(no_unnecessary_cast): fix typo in shallow

### PR DESCRIPTION
**Pull request by ChaoticRoman**
Just small typo fix

### CODE REVIEW

**Review by dosisod — APPROVED** [review]
Good catch!

**Comment by dosisod** [comment]
Also @ChaoticRoman , the email address you're using to make commits doesn't match your GitHub email, which is why your GitHhub avatar isn't showing up next to your commit messages. Just thought you should know that!

**Comment by ChaoticRoman** [comment]
> Also @ChaoticRoman , the email address you're using to make commits doesn't match your GitHub email, which is why your GitHhub avatar isn't showing up next to your commit messages. Just thought you should know that!

Yay, you are right, that is indeed mistake. Let's leave it like this, there isn't any harm caused by this and I will be more careful next time.

**Comment by dosisod** [comment]
No worries! I was letting you know for your own sake.

**Pull request merged**
