### PR TITLE
add `simplify-split` check

### PR DESCRIPTION
**Pull request by jayceslesar**
Followed the changes detailed from https://github.com/dosisod/refurb/pull/275 and used [print](https://github.com/dosisod/refurb/blob/master/refurb/checks/builtin/print.py) to guide the solution

### CODE REVIEW

**Comment by dosisod** [comment]
Thank you for your contribution! Unfortunately, `split(" ")` is not the same as `split()`, as `split` without an argument will split on all whitespace, not just the space character. For example:

```python
>>> data = "hello there\tworld"

>>> data.split(" ")
['hello', 'there\tworld']

>>> data.split()
['hello', 'there', 'world']

>>> data.split(None)
['hello', 'there', 'world']

>>> "".split(" ")
['']

>>> "".split()
[]
```

`split(None)` is the same as `split()` though, so we could update this to include that instead. If that is the case though, we would be better off adding a `str.split(None)` entry to FURB120, since that check already detects default arguments in the stdlib.

**Comment by jayceslesar** [comment]
Does that just consist of updating the mapping here? https://github.com/dosisod/refurb/blob/master/refurb/checks/function/use_implicit_default.py#L64C1-L64C17

**Comment by dosisod** [comment]
@jayceslesar Yep! It isn't really documented, but basically `...` is any argument or type, whereas `NoneNode`, `IntExpr(123)`, and `StringExpr("xyz")` correspond to `None`, `123`, and `"xyz"` respectively.

**Comment by jayceslesar** [comment]
> @jayceslesar Yep! It isn't really documented, but basically `...` is any argument or type, whereas `NoneNode`, `IntExpr(123)`, and `StringExpr("xyz")` correspond to `None`, `123`, and `"xyz"` respectively.

sounds good! I will close this and make a new PR

**Comment by jayceslesar** [comment]
@dosisod I did try this for a bit but I dont think that the `use_implicit_default` check is working because `poetry run refurb test/data/err_120.py` doesn't even yield any output

**Comment by dosisod** [comment]
Try adding the flag `--enable FURB120` to the command. FURB120 is disabled by default, so that's probably why you're not seeing any output.

**Comment by jayceslesar** [comment]
yeah my file looks like 
```py
"".split(None)

# round(1, 0)
```

and I am running `poetry run refurb --enable FURB120 asdf.py` on latest main and I dont see any output when it is just `"".split(None)` but when I uncomment  `round(1, 0)` I get the 120 message

**Comment by dosisod** [comment]
Oh, I see what you mean. Currently FURB120 only detects `x.get("key", None)`, not `{}.get("key", None)`. That's probably why `"".split(None)` isn't working for you. If you try:

```
s = ""
s.split(None)
```

then it should work.

**Pull request closed without merging**
